-- TransactionDisputePortal — Docker init script
-- Runs once when the Postgres data directory is first initialised.
-- Column names MUST match EF Core model conventions:
--   • Properties with [Column("snake_case")] → snake_case column names
--   • Properties without [Column] → PascalCase column names (EF quotes all identifiers)

-- ────────────────────────────────────────────────────────────
-- 1. EF Migrations history — marks our migration as applied so
--    EF Core does NOT attempt to re-create tables at startup.
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId"    varchar(150) NOT NULL,
    "ProductVersion" varchar(32)  NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260627204905_AddUsersAndDisputeLocking', '10.0.9')
ON CONFLICT DO NOTHING;

-- ────────────────────────────────────────────────────────────
-- 2. Schema
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Users" (
    "Id"           serial       PRIMARY KEY,
    "Username"     varchar(100) NOT NULL,
    "PasswordHash" text         NOT NULL,
    "FullName"     varchar(200) NOT NULL,
    "Role"         varchar(50)  NOT NULL,
    "IsActive"     boolean      NOT NULL DEFAULT true,
    "CreatedAt"    timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Username" ON "Users" ("Username");

CREATE TABLE IF NOT EXISTS "Transactions" (
    "Id"               serial       PRIMARY KEY,
    "customer_id"      int          NOT NULL,
    "transaction_uid"  text         NOT NULL,
    "Amount"           numeric      NOT NULL,
    "Description"      varchar(500) NOT NULL,
    "transaction_date" timestamp with time zone NOT NULL,
    "Merchant"         varchar(200) NOT NULL,
    "Category"         varchar(100) NOT NULL,
    "Status"           int          NOT NULL,
    "created_at"       timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "Disputes" (
    "Id"                serial        PRIMARY KEY,
    "transaction_id"    int           NOT NULL,
    "customer_id"       int           NOT NULL,
    "Reason"            varchar(100)  NOT NULL,
    "Description"       varchar(1000) NOT NULL,
    "Status"            int           NOT NULL,
    "created_at"        timestamp with time zone NOT NULL,
    "resolved_at"       timestamp with time zone,
    "resolution_notes"  varchar(1000),
    "refund_amount"     numeric,
    "transaction_id_fk" int           NOT NULL,
    "locked_by_user_id" int,
    "locked_by_name"    varchar(200),
    "locked_at"         timestamp with time zone,
    CONSTRAINT "FK_Disputes_Transactions_transaction_id_fk"
        FOREIGN KEY ("transaction_id_fk") REFERENCES "Transactions" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Disputes_transaction_id_fk" ON "Disputes" ("transaction_id_fk");

-- ────────────────────────────────────────────────────────────
-- 3. Seed data (hashes generated by ASP.NET Identity PasswordHasher v3)
--    Plaintext: Admin123! / Banker123! / Banker2123! / Client123! / Readonly123!
-- ────────────────────────────────────────────────────────────
INSERT INTO "Users" ("Id","Username","PasswordHash","FullName","Role","IsActive","CreatedAt") VALUES
(1,'admin',   'AQAAAAIAAYagAAAAEHAs/RIAc73AdUmTE7pE4RVjRetn/52Beuma5Na3CJMmGHUdapIb+5sGC9YsQtAJpQ==','Admin User',    'Admin',    true,'2026-01-01 00:00:00+00'),
(2,'banker',  'AQAAAAIAAYagAAAAEOHyOmsU4MC6cbFkFAa+waEQdy+yk4gTy5+rYWpjb4czzqDtnl2zJo1VzcwUCl66Hw==','Banker One',    'Banker',   true,'2026-01-01 00:00:00+00'),
(3,'banker2', 'AQAAAAIAAYagAAAAEIyDrUA+t6w5xyCy4Ukf/48KkJEIfkud1OztXcUdbN4vWmU5dNE3AhWH0PdEBjLF6g==','Banker Two',    'Banker',   true,'2026-01-01 00:00:00+00'),
(4,'client',  'AQAAAAIAAYagAAAAEOVwhOITRao7qU1Cf2fQ1xXychGjsufGSLJ5LDdkzoDg5AmskD5O1mdUyW3J8xXznQ==','Client User',   'Client',   true,'2026-01-01 00:00:00+00'),
(5,'readonly','AQAAAAIAAYagAAAAEKZeA/2pDqEoc2E/79npcng/NBYPhpwZeLWQd0PnaxFEkATi7CgrnHuvyVFCH8We1Q==','ReadOnly User', 'ReadOnly', true,'2026-01-01 00:00:00+00')
ON CONFLICT DO NOTHING;

INSERT INTO "Transactions" ("Id","customer_id","transaction_uid","Amount","Description","transaction_date","Merchant","Category","Status","created_at") VALUES
(1,4,'TXN20260604001',1250.50,'ATM Withdrawal',            '2026-06-17 00:00:00+00','FNB ATM - Sandton',            'ATM Withdrawal',  0,'2026-06-17 00:00:00+00'),
(2,4,'TXN20260609002', 899.99,'Monthly Insurance Premium', '2026-06-22 00:00:00+00','Old Mutual Insurance',         'Insurance',       0,'2026-06-22 00:00:00+00'),
(3,4,'TXN20260612003', 450.00,'Utility Payment',           '2026-06-25 00:00:00+00','Eskom - Electricity',          'Utilities',       0,'2026-06-25 00:00:00+00'),
(4,4,'TXN20260520004',2000.00,'International Wire Transfer','2026-06-02 00:00:00+00','Standard Chartered Bank - USA','Wire Transfer',   0,'2026-06-02 00:00:00+00'),
(5,4,'TXN20260614005', 325.50,'Card Purchase',              '2026-06-26 00:00:00+00','Pick n Pay - Westgate',        'Retail',          0,'2026-06-26 00:00:00+00'),
(6,4,'TXN20260615006', 150.00,'Mobile Top-Up',              '2026-06-27 00:00:00+00','Vodacom South Africa',         'Mobile Services', 0,'2026-06-27 00:00:00+00')
ON CONFLICT DO NOTHING;

INSERT INTO "Disputes" ("Id","transaction_id","customer_id","Reason","Description","Status","created_at","resolved_at","resolution_notes","refund_amount","transaction_id_fk") VALUES
(1,1,4,'Unauthorized',    'I did not authorize this ATM withdrawal',1,'2026-06-24 00:00:00+00',NULL,NULL,1250.50,1),
(2,4,4,'Incorrect Amount','Wire transfer was charged twice',        2,'2026-06-07 00:00:00+00','2026-06-12 00:00:00+00','Duplicate charge refunded to account',2000.00,4)
ON CONFLICT DO NOTHING;

-- ────────────────────────────────────────────────────────────
-- 4. Advance sequences past the highest seeded ID so EF Core
--    auto-generated IDs never collide with seed rows.
-- ────────────────────────────────────────────────────────────
SELECT setval(pg_get_serial_sequence('"Users"',        'Id'), (SELECT MAX("Id") FROM "Users"));
SELECT setval(pg_get_serial_sequence('"Transactions"', 'Id'), (SELECT MAX("Id") FROM "Transactions"));
SELECT setval(pg_get_serial_sequence('"Disputes"',     'Id'), (SELECT MAX("Id") FROM "Disputes"));

