// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransactionDisputePortal.Api.Data;

#nullable disable

namespace TransactionDisputePortal.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransactionDisputePortal.Api.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEHAs/RIAc73AdUmTE7pE4RVjRetn/52Beuma5Na3CJMmGHUdapIb+5sGC9YsQtAJpQ==",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Banker One",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEOHyOmsU4MC6cbFkFAa+waEQdy+yk4gTy5+rYWpjb4czzqDtnl2zJo1VzcwUCl66Hw==",
                            Role = "Banker",
                            Username = "banker"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Banker Two",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEIyDrUA+t6w5xyCy4Ukf/48KkJEIfkud1OztXcUdbN4vWmU5dNE3AhWH0PdEBjLF6g==",
                            Role = "Banker",
                            Username = "banker2"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Client User",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEOVwhOITRao7qU1Cf2fQ1xXychGjsufGSLJ5LDdkzoDg5AmskD5O1mdUyW3J8xXznQ==",
                            Role = "Client",
                            Username = "client"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "ReadOnly User",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEKZeA/2pDqEoc2E/79npcng/NBYPhpwZeLWQd0PnaxFEkATi7CgrnHuvyVFCH8We1Q==",
                            Role = "ReadOnly",
                            Username = "readonly"
                        });
                });

            modelBuilder.Entity("TransactionDisputePortal.Api.Models.Dispute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("locked_by_name");

                    b.Property<int?>("LockedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("locked_by_user_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("refund_amount");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    b.Property<int>("TransactionIdFk")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id_fk");

                    b.HasKey("Id");

                    b.HasIndex("TransactionIdFk");

                    b.ToTable("Disputes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            Description = "I did not authorize this ATM withdrawal",
                            Reason = "Unauthorized",
                            RefundAmount = 1250.50m,
                            Status = 1,
                            TransactionId = 1,
                            TransactionIdFk = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            Description = "Wire transfer was charged twice",
                            Reason = "Incorrect Amount",
                            RefundAmount = 2000.00m,
                            ResolutionNotes = "Duplicate charge refunded to account",
                            ResolvedAt = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            TransactionId = 4,
                            TransactionIdFk = 4
                        });
                });

            modelBuilder.Entity("TransactionDisputePortal.Api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_uid");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1250.50m,
                            Category = "ATM Withdrawal",
                            CreatedAt = new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            Description = "ATM Withdrawal",
                            Merchant = "FNB ATM - Sandton",
                            Status = 0,
                            TransactionDate = new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionId = "TXN20260604001"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 899.99m,
                            Category = "Insurance",
                            CreatedAt = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            Description = "Monthly Insurance Premium",
                            Merchant = "Old Mutual Insurance",
                            Status = 0,
                            TransactionDate = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionId = "TXN20260609002"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 450.00m,
                            Category = "Utilities",
                            CreatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            Description = "Utility Payment",
                            Merchant = "Eskom - Electricity",
                            Status = 0,
                            TransactionDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionId = "TXN20260612003"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2000.00m,
                            Category = "Wire Transfer",
                            CreatedAt = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            Description = "International Wire Transfer",
                            Merchant = "Standard Chartered Bank - USA",
                            Status = 0,
                            TransactionDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionId = "TXN20260520004"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 325.50m,
                            Category = "Retail",
                            CreatedAt = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            Description = "Card Purchase",
                            Merchant = "Pick n Pay - Westgate",
                            Status = 0,
                            TransactionDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionId = "TXN20260614005"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 150.00m,
                            Category = "Mobile Services",
                            CreatedAt = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            Description = "Mobile Top-Up",
                            Merchant = "Vodacom South Africa",
                            Status = 0,
                            TransactionDate = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionId = "TXN20260615006"
                        });
                });

            modelBuilder.Entity("TransactionDisputePortal.Api.Models.Dispute", b =>
                {
                    b.HasOne("TransactionDisputePortal.Api.Models.Transaction", "Transaction")
                        .WithMany("Disputes")
                        .HasForeignKey("TransactionIdFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("TransactionDisputePortal.Api.Models.Transaction", b =>
                {
                    b.Navigation("Disputes");
                });
#pragma warning restore 612, 618
        }
    }
}
